"""Side-aware BTCTurk order sizing.

BTCTurk's REST API has an important asymmetry which a generic Hummingbot
connector cannot safely hide: a market BUY ``quantity`` is a quote-currency
amount (TRY for TRY markets), while a market SELL ``quantity`` is a base
amount. Strategies and the recovery engine work in base amounts. This module
is dependency-free so the conversion can be tested in isolation and reused
by an explicit, guarded recovery path.
"""

from dataclasses import dataclass
from decimal import Decimal, ROUND_UP
from typing import Optional


ZERO = Decimal("0")


class OrderSemanticsError(ValueError):
    """Raised when an exchange order would be ambiguous or unsafe."""


class InsufficientQuoteBalance(OrderSemanticsError):
    """The quote amount, including safety reserves, is not available."""


@dataclass(frozen=True)
class MarketBuyQuote:
    """A fully validated BTCTurk market-BUY quote amount."""

    requested_base: Decimal
    reference_price: Decimal
    fee_buffer_try: Decimal
    quote_quantity_try: Decimal
    available_try: Optional[Decimal]
    min_quote_try: Decimal
    quote_step: Decimal


def _positive(value: Decimal, name: str) -> Decimal:
    value = Decimal(value)
    if not value.is_finite() or value <= ZERO:
        raise OrderSemanticsError(f"{name} must be positive")
    return value


def _non_negative(value: Decimal, name: str) -> Decimal:
    value = Decimal(value)
    if not value.is_finite() or value < ZERO:
        raise OrderSemanticsError(f"{name} must be non-negative")
    return value


def quantize_up(value: Decimal, step: Decimal) -> Decimal:
    """Round a positive amount upward to an exchange precision step."""

    value = _positive(value, "value")
    step = _positive(step, "step")
    return (value / step).to_integral_value(rounding=ROUND_UP) * step


def market_buy_quote_for_base(
    *,
    base_amount: Decimal,
    reference_price: Decimal,
    fee_rate: Decimal,
    safety_buffer_rate: Decimal,
    available_try: Optional[Decimal],
    min_quote_try: Decimal = ZERO,
    quote_step: Decimal = Decimal("0.01"),
    max_quote_try: Optional[Decimal] = None,
) -> MarketBuyQuote:
    """Convert a base target to a validated BTCTurk market-BUY quote.

    ``reference_price`` must come from a fresh ask/VWAP snapshot. The fee and
    safety rates are applied before precision rounding. If the rounded quote
    exceeds either the authenticated available TRY balance or an optional
    configured maximum, this fails closed before an HTTP request.
    """

    base_amount = _positive(base_amount, "base_amount")
    reference_price = _positive(reference_price, "reference_price")
    fee_rate = _non_negative(fee_rate, "fee_rate")
    safety_buffer_rate = _non_negative(safety_buffer_rate, "safety_buffer_rate")
    min_quote_try = _non_negative(min_quote_try, "min_quote_try")
    quote_step = _positive(quote_step, "quote_step")
    if available_try is not None:
        available_try = _non_negative(available_try, "available_try")
    if max_quote_try is not None:
        max_quote_try = _positive(max_quote_try, "max_quote_try")

    gross_quote = base_amount * reference_price
    fee_buffer_try = gross_quote * (fee_rate + safety_buffer_rate)
    required_quote = gross_quote + fee_buffer_try
    quote_quantity = quantize_up(max(required_quote, min_quote_try), quote_step)

    if max_quote_try is not None and quote_quantity > max_quote_try:
        raise OrderSemanticsError("market-BUY quote exceeds configured maximum")
    if available_try is not None and quote_quantity > available_try:
        raise InsufficientQuoteBalance(
            f"market-BUY requires {quote_quantity} TRY; only {available_try} TRY is available"
        )
    return MarketBuyQuote(
        requested_base=base_amount,
        reference_price=reference_price,
        fee_buffer_try=fee_buffer_try,
        quote_quantity_try=quote_quantity,
        available_try=available_try,
        min_quote_try=min_quote_try,
        quote_step=quote_step,
    )


def build_market_order_payload(
    *,
    client_order_id: str,
    symbol: str,
    side: str,
    base_amount: Decimal,
    market_buy_quote: Optional[MarketBuyQuote] = None,
) -> dict[str, str]:
    """Build a BTCTurk market payload without losing side semantics.

    A BUY must receive a :class:`MarketBuyQuote` generated by the preflight
    converter. A SELL keeps the requested base quantity. Requiring the
    converter object for BUY makes it impossible for a caller to accidentally
    put a coin amount into BTCTurk's TRY-sized field.
    """

    normalized_side = side.lower()
    if normalized_side not in {"buy", "sell"}:
        raise OrderSemanticsError("side must be buy or sell")
    base_amount = _positive(base_amount, "base_amount")
    if normalized_side == "buy":
        if market_buy_quote is None:
            raise OrderSemanticsError("market BUY requires a validated TRY quote")
        if market_buy_quote.requested_base != base_amount:
            raise OrderSemanticsError("market BUY quote does not match base amount")
        quantity = market_buy_quote.quote_quantity_try
    else:
        if market_buy_quote is not None:
            raise OrderSemanticsError("market SELL must not receive a BUY quote")
        quantity = base_amount
    return {
        "quantity": format(quantity, "f"),
        "newOrderClientId": client_order_id,
        "orderMethod": "market",
        "orderType": normalized_side,
        "pairSymbol": symbol.upper(),
    }


def build_side_aware_order_payload(
    *,
    client_order_id: str,
    symbol: str,
    side: str,
    order_method: str,
    base_amount: Decimal,
    price: Optional[Decimal] = None,
    market_buy_quote: Optional[MarketBuyQuote] = None,
) -> dict[str, str]:
    """Build either a limit or explicitly preflighted market order payload."""

    normalized_method = order_method.lower()
    if normalized_method == "limit":
        if price is None:
            raise OrderSemanticsError("limit order requires price")
        price = _positive(price, "price")
        if market_buy_quote is not None:
            raise OrderSemanticsError("limit order must not receive a market BUY quote")
        normalized_side = side.lower()
        if normalized_side not in {"buy", "sell"}:
            raise OrderSemanticsError("side must be buy or sell")
        return {
            "quantity": format(_positive(base_amount, "base_amount"), "f"),
            "price": format(price, "f"),
            "newOrderClientId": client_order_id,
            "orderMethod": "limit",
            "orderType": normalized_side,
            "pairSymbol": symbol.upper(),
        }
    if normalized_method == "market":
        return build_market_order_payload(
            client_order_id=client_order_id,
            symbol=symbol,
            side=side,
            base_amount=base_amount,
            market_buy_quote=market_buy_quote,
        )
    raise OrderSemanticsError("order_method must be limit or market")

