version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    environment:
      APP_HOST: yumtech-tv_web_1
      APP_PORT: 8097
      PROXY_AUTH_WHITELIST: /api/*

  web:
    image: nginx:1.27-alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/web:/usr/share/nginx/html:ro
      - ${APP_DATA_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8097/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
