events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;
  keepalive_timeout 65;

  server {
    listen 8097;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
      add_header Cache-Control "no-cache";
    }

    location ~* \.(?:css|js|svg|png|jpg|jpeg|webp|ico)$ {
      try_files $uri =404;
      add_header Cache-Control "public, max-age=3600";
    }
  }
}
